// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FHqy1WbMQxUoP8uUIlQlkEwY5ZIf8EQ',
    appId: '1:783368917506:web:d8839206a1ccf4189b8d1b',
    messagingSenderId: '783368917506',
    projectId: 'asroo-store-9d51a',
    authDomain: 'asroo-store-9d51a.firebaseapp.com',
    storageBucket: 'asroo-store-9d51a.firebasestorage.app',
    measurementId: 'G-ZXST5S5S8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1D9Ux57vyKXiHKOAKhZ7tagQqD_VRxuc',
    appId: '1:783368917506:android:a10a3322f00aea2f9b8d1b',
    messagingSenderId: '783368917506',
    projectId: 'asroo-store-9d51a',
    storageBucket: 'asroo-store-9d51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUzHjJljS4hlTnbFUyh6uyyltvbvRQTg',
    appId: '1:783368917506:ios:50a5b5f8f7e570c19b8d1b',
    messagingSenderId: '783368917506',
    projectId: 'asroo-store-9d51a',
    storageBucket: 'asroo-store-9d51a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUzHjJljS4hlTnbFUyh6uyyltvbvRQTg',
    appId: '1:783368917506:ios:50a5b5f8f7e570c19b8d1b',
    messagingSenderId: '783368917506',
    projectId: 'asroo-store-9d51a',
    storageBucket: 'asroo-store-9d51a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4FHqy1WbMQxUoP8uUIlQlkEwY5ZIf8EQ',
    appId: '1:783368917506:web:adc9536153f872bd9b8d1b',
    messagingSenderId: '783368917506',
    projectId: 'asroo-store-9d51a',
    authDomain: 'asroo-store-9d51a.firebaseapp.com',
    storageBucket: 'asroo-store-9d51a.firebasestorage.app',
    measurementId: 'G-SJT1CS9S9D',
  );
}
