analyzer:
  errors:
    inference_failure_on_untyped_parameter: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    sort_pub_dependencies: false
    one_member_abstracts: false
