name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4

# Dependencies - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dependencies:
  animate_do: ^3.3.4
  badges: ^3.1.2
  bloc_concurrency: ^0.2.5

  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  # easy_dynamic_link: ^0.0.1
  # firebase_dynamic_links: ^5.4.15
  equatable: ^2.0.7
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.15
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^8.2.8

  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  hive_flutter: ^1.1.0

  image_picker: ^1.1.2
  intl: ^0.19.0

  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1

  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0

  webview_flutter: ^4.10.0

# Dev.Dependencies - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13 # dart run build_runner build --delete-conflicting-outputs
  freezed: ^2.5.7
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  assets:
    - envs/.env.dev
    - envs/.env.prod
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/
    - assets/icons/

  # Fonts - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/Poppins-Regular.ttf
          weight: 400
